version: '3.3'
services:
  spider-mail:
    image: app-nx.marcoshssilva.com.br/x86-64/marcoshssilva/spidermail-custom:latest
    restart: on-failure
    ports:
      - 25:25
      - 993:993
      - 8080:8080
    volumes:
      - spider-data:/opt/spider
    networks:
      - spider-network
volumes:
  spider-data:
networks:
  spider-network:
    driver: bridge